
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from datetime import datetime
import matplotlib.pyplot as plt

def _chart_stage_counts(stage_counts, out_png_path: str):
    labels = list(stage_counts.index)
    values = list(stage_counts.values)
    plt.figure()
    plt.bar(labels, values)
    plt.xlabel("Stage")
    plt.ylabel("Count")
    plt.title("Candidates by Stage")
    plt.tight_layout()
    plt.savefig(out_png_path)
    plt.close()

def generate_pdf_report(pdf_path: str, kpis: dict, stage_counts, stuck_df):
    chart_path = pdf_path.replace(".pdf", "_stage_chart.png")
    _chart_stage_counts(stage_counts, chart_path)

    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4
    x_margin, y_margin = 2*cm, 2*cm
    y = height - y_margin

    c.setFont("Helvetica-Bold", 16)
    c.drawString(x_margin, y, "Interview Pipeline Insights — Summary Report")
    y -= 1.0*cm

    c.setFont("Helvetica", 10)
    c.drawString(x_margin, y, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    y -= 1.0*cm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_margin, y, "Key Metrics")
    y -= 0.6*cm
    c.setFont("Helvetica", 11)
    c.drawString(x_margin, y, f"Total Candidates: {kpis.get('total', 0)}")
    y -= 0.5*cm
    c.drawString(x_margin, y, f"Avg. Time to Hire (days): {kpis.get('avg_time_to_hire_days') or 0}")
    y -= 0.5*cm
    c.drawString(x_margin, y, f"Conversion (Offer+Hired / All): {kpis.get('conversion_pct') or 0}%")
    y -= 1.0*cm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_margin, y, "Candidates by Stage")
    y -= 0.5*cm
    chart_w = 12*cm
    chart_h = 6*cm
    c.drawImage(chart_path, x_margin, y - chart_h, width=chart_w, height=chart_h, preserveAspectRatio=True, mask='auto')
    y -= chart_h + 0.8*cm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_margin, y, "Bottlenecks (stuck candidates)")
    y -= 0.6*cm
    c.setFont("Helvetica", 10)
    if stuck_df is None or stuck_df.empty:
        c.drawString(x_margin, y, "None detected for the selected threshold.")
        y -= 0.5*cm
    else:
        max_items = 12
        for _, row in stuck_df.head(max_items).iterrows():
            line = f"- {row['Candidate']} ({row['Role']}), Stage: {row['Stage']}, Last Updated: {row['Last_Updated'].date()}, Applied: {row['Applied_Date'].date()}"
            c.drawString(x_margin, y, line)
            y -= 0.45*cm

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(x_margin, y_margin, "Generated by Interview Pipeline Insights (Streamlit + Python)")
    c.save()
